### ISSUE TITLE
1st try, no success

### ISSUE THREAD

**Issue by sm3ulc** [Guenael/rtlsdr-ft8d#30]
Dongle, rtlsdr-v3
Antenna longwire tuned for 30m-band.
OS, Ubuntu, standard PC
Clock ok
WSJT-X logging about ~20 calls per slot.

```
ntpq -p
remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
*192.168.1.4 (nt .PPS.            1 u   38   64  377    0.196    0.124   0.385
+sth1.ntp.netnod .PPS.            1 u   43   64  377    2.031    0.573   0.372
+sth2.ntp.netnod .PPS.            1 u   39   64  377    1.881    0.086   5.751
```

```
./rtlsdr_ft8d -f 7074k -g 25 -d 2 -c call -l loc -i 1 -n 1
Found 2 device(s):
  0:  Realtek, RTL2838UHIDIR, SN: 06001049
  1:  Realtek, RTL2838UHIDIR, SN: 00000010

Using device 1: Generic RTL2832U OEM
Found Rafael Micro R820T tuner
Enabled direct sampling mode, input 2

Starting rtlsdr-ft8d (2021-12-07, 19:04z) -- Version 0.1alpha
  Callsign     : q
  Locator      : q
  Dial freq.   : 7074000 Hz
  Real freq.   : 7074000 Hz
  PPM factor   : 0
  Gain         : 25 dB
Wait for time sync (start in 5 sec)

Date  Time(z)    SNR     DT       Freq Dr    Call    Loc Pwr
Allocating 15 zero-copy buffers
Max magnitude: -56.6 dB
LDPC decode: 10 errors
LDPC decode: 6 errors
LDPC decode: 18 errors
LDPC decode: 7 errors
LDPC decode: 21 errors
Decoded 0 messages
Max magnitude: -56.6 dB
LDPC decode: 12 errors
LDPC decode: 6 errors
LDPC decode: 18 errors
LDPC decode: 7 errors
LDPC decode: 21 errors
Decoded 0 messages
```

**Comment by F5LEN** [comment]
Same on 2m with two devices.

Found 1 device(s):
  0:  Realtek, RTL2838UHIDIR, SN: 00000001

Using device 0: Generic RTL2832U OEM
Found Rafael Micro R820T tuner
[R82XX] PLL not locked!

Starting rtlsdr-ft8d (2021-12-07, 21:48z) -- Version 0.1alpha
  Callsign     : F8KID
  Locator      : JN38AT
  Dial freq.   : 144489000 Hz
  Real freq.   : 144489000 Hz
  PPM factor   : 0
  Gain         : 29 dB
Wait for time sync (start in 1 sec)

              Date  Time(z)    SNR     DT       Freq Dr    Call    Loc Pwr
Allocating 15 zero-copy buffers
Max magnitude: -48.0 dB
LDPC decode: 22 errors
LDPC decode: 16 errors
LDPC decode: 83 errors
LDPC decode: 83 errors
LDPC decode: 83 errors
LDPC decode: 19 errors
LDPC decode: 14 errors
LDPC decode: 5 errors
Decoded 0 messages
Max magnitude: -48.6 dB
LDPC decode: 4 errors
LDPC decode: 83 errors
LDPC decode: 9 errors
LDPC decode: 5 errors
LDPC decode: 4 errors
Decoded 0 messages

Even with a local (strong) signal.

**Comment by F5LEN** [comment]
Same with 2 different devices

` Found 1 device(s):
  0:  Realtek, RTL2838UHIDIR, SN: 00000001

Using device 0: Generic RTL2832U OEM
Found Rafael Micro R820T tuner
[R82XX] PLL not locked!

Starting rtlsdr-ft8d (2021-12-07, 21:48z) -- Version 0.1alpha
  Callsign     : F8KID
  Locator      : JN38AT
  Dial freq.   : 144174000 Hz
  Real freq.   : 144174000 Hz
  PPM factor   : 0
  Gain         : 29 dB
Wait for time sync (start in 1 sec)

              Date  Time(z)    SNR     DT       Freq Dr    Call    Loc Pwr
Allocating 15 zero-copy buffers
Max magnitude: -48.0 dB
LDPC decode: 22 errors
LDPC decode: 16 errors
LDPC decode: 83 errors
LDPC decode: 83 errors
LDPC decode: 83 errors
LDPC decode: 19 errors
LDPC decode: 14 errors
LDPC decode: 5 errors
Decoded 0 messages
Max magnitude: -48.6 dB
LDPC decode: 4 errors
LDPC decode: 83 errors
LDPC decode: 9 errors
LDPC decode: 5 errors
LDPC decode: 4 errors
Decoded 0 messages
 `

same with a local station (strong signal). No decode.

**Comment by Guenael** [comment]
Well... not working like expected, the fun start here :)

It could be an issue with an 1.5kHz offset, but on an HF band, there is always some traffic to catch...

**Comment by Guenael** [comment]
Let's try with the easy/common stuff.
I made a quick patch, here : https://github.com/Guenael/rtlsdr-ft8d/pull/35
Let me know!

**Comment by F5LEN** [comment]
No luck.
Applying the patch this morning. Same result even if the 1500 Hz shift is ok.

**Comment by Guenael** [comment]
I will write a self-test function + read write exporter.
Thanks for your reports!

**Comment by Guenael** [comment]
Some good news!! The self-test function works, and there are read/write functions to store records and debug them.

```
> ./rtlsdr_ft8d -t
SNR  DT   Freq ~ Message
 34 -0.08   28 ~ CQ K1JT FN20
1 decoded messages
Self-test SUCCESS!
```

**Comment by Guenael** [comment]
@sm3ulc @F5LEN : 1st try didn't works, let's do another one! :)

I made a big commit, with an auto-test feature, and read/save functions (-w & -r).
The self-test works, and a external test file was successfully decoded, but some issues with the baseband front-end can remains.

For now, the bandwidth is only 1.6kHz, so you have to pinpoint the exact frequency.
You can store an IQ files, and open it with Audacity. Use these parameters for Audacity:
- Import RAW data
- Encoding: Float32
- Byte order: Little endian
- 2 Channels
- 3200 sample/sec
- After, use the Spectrogram

Sample duration should be exactly 15 secs, and you should be able to see your FT8 signals over some white noise.

You could have to add 1kHz to your usual frequency. rtlsd-ft8d only see +/-800 Hz around the dial frequency for now (I can fix this).

If it didn't find any spot, we still have a second chance (ahh, lottery...). You can check this loop : https://github.com/Guenael/rtlsdr-ft8d/blob/main/rtlsdr_ft8d.c#L1105

```c
for (int i = 0; i < NFFT; ++i) {
    fft_in[i][0] = iSamples[(idx_block * BLOCK_SIZE) + (time_sub * SUB_BLOCK_SIZE) + i] * hann[i];
    fft_in[i][1] = qSamples[(idx_block * BLOCK_SIZE) + (time_sub * SUB_BLOCK_SIZE) + i] * hann[i];
}
```

and try to exchange `iSamples` and `qSamples`, or use `-qSamples` instead.

If it didn't work, please post your IQ sample here.

Thanks! 73

**Comment by F5LEN** [comment]
Hi Guenael,
I checked today.
Still not working here sorry. I setup a RPI 4 for a try but no more luck.
Pse have a look at sample.zip .
In it 3 files k_2021-12-12_15-37-50.iq, k_2021-12-12_15-38-20 and k_2021-12-12_15-38-50 made with a local transmission on air. I'm confuse beacause I can see the FT8 signal. The duration is 15s. But there is something wrong with the time.
The FT8 signal seems at the end of the recording. The computer are ok with time (ntp on each).

So I try to send a manual tune on 2 periods. 1st period 3 tunes.
Second period 4 tune.
See the file k_2021-12-12_15-40-20.iq, we can see the 3 first tune of the first period but also the tunes in the second period.

In audacity signal sounds dirty.

73 Pascal
[sample.zip](https://github.com/Guenael/rtlsdr-ft8d/files/7699033/sample.zip)

**Comment by Guenael** [comment]
@F5LEN Thanks for your report. You pinpointed 2 issues:
- Time sync
- Modulated signal (during the decimation stage I guess, if your are sure that you didn't overdrive the input stage of the RTL, cf. gain)

**Comment by Guenael** [comment]
Some progress, the sync works fine on Linux x86_64, but not a RPi (with ntpd working properly on both). It's a funny issue...

**Comment by Guenael** [comment]
For any further test, please use a Linux x86 machine, and not a Raspberry Pi.
I'm not sure what's wrong with the RPi, but there are:
- Timing issue (with time_t & struct timeval)
- Sampling issue (should sample at 2.4MHz but it's more close to 1.8MHz in practice

**Comment by F5LEN** [comment]
Ouch!
The only x86 machine I have  are VMs...
Anyway, i will setup a new one in the shack.

**Comment by Guenael** [comment]
@F5LEN well, it's only for testing/debugging on another arch, because I have no clue on this issue with RPi devices.

I did all my tests on a RPi4, and I'm re-installing an RPi2, any everything is so slow on an SD-Card... :) RPi4 allows USB booting, and it's definitely a nice feature.

Anyway, I will check the sync & sampling on a RPi1,2,3&4. We will see. rtlsdr-wspr is broken too, and I'm pretty sure this is the same bug.

Thanks again for your help.

**Comment by Guenael** [comment]
OK, I just get it... It's a kind of performance issue, the callback function don't get the sample fast enough. And of course, it takes more time to get the exact number of sample wanted (ex. 20sec instead of 15s for a FT8 transmission).

The CPU is capable to deal the decimation (a RPi1 was able to do the job), so I guess it's something else (api call, delay etc...)

I will try to run an old version of rtlsdr-wsprd to be sure the problem still exist, we will see.

**Comment by Guenael** [comment]
CPU issue fixed, with the manual installation of `rtl-sdr`.

Explanation here: https://github.com/Guenael/rtlsdr-wsprd/issues/59#issuecomment-995290669
And documentation updated: https://github.com/Guenael/rtlsdr-ft8d#installation

I published a new release, I hope you will be able to decode something this time!

Notes: 
- The first decoding is incomplete #known-bug
- You can record some samples (check the options)
- For now, the spots are not uploaded to PSKrepoter (I have to write this part).
- If you don't decode anything, you can still try this fix (IQ inversion):
  *check this loop : https://github.com/Guenael/rtlsdr-ft8d/blob/main/rtlsdr_ft8d.c#L1105*
  ```c
  for (int i = 0; i < NFFT; ++i) {
    fft_in[i][0] = iSamples[(idx_block * BLOCK_SIZE) + (time_sub * SUB_BLOCK_SIZE) + i] * hann[i];
    fft_in[i][1] = qSamples[(idx_block * BLOCK_SIZE) + (time_sub * SUB_BLOCK_SIZE) + i] * hann[i];
  }
  ```
  *and try to exchange iSamples and qSamples, or use -qSamples instead.*

73

**Comment by mkarliner** [comment]
I still have the LPC errors, and this is on a Pi with a now working wsprd.
CPU usage is OK at 17% of a Pi 3A +

**Comment by Guenael** [comment]
@mkarliner LDPC errors? I removed these DBG message on the latest version, did you fetch the latest version, or did you enabled these printf?

**Comment by F5LEN** [comment]
Hi !
It's working with a local signal
![image](https://user-images.githubusercontent.com/95721577/146518383-505b760a-13a3-4f63-a593-cdaafdf2d496.png)
Need to wait a bit for other decode.

**Comment by Guenael** [comment]
Excellent!! Thank for this update :)

**Comment by Guenael** [comment]
I still have to write the PSKreporter function (cannot use curl on this one...)
